---
apiVersion: codemowers.io/v1alpha1
kind: Secret
metadata:
  name: etherpad
spec:
  mapping:
    - key: ADMIN_PASSWORD
      value: "%(password)s"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etherpad
spec:
  replicas: 1
  serviceName: etherpad
  selector:
    matchLabels:
      app: etherpad
  template:
    metadata:
      labels:
        app: etherpad
    spec:
      containers:
        - name: etherpad
          image: etherpad/etherpad:1
          securityContext:
            # Etherpad writes session key during start
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 5001
          ports:
            - containerPort: 9001
          env:
            - name: DB_TYPE
              value: mysql
            - name: DB_HOST
              value: mysql-standalone
            - name: DB_NAME
              value: etherpad
            - name: DB_USER
              value: root
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-standalone-secrets
                  key: rootPassword
            - name: PAD_OPTIONS_NO_COLORS
              value: "true"
            - name: PAD_OPTIONS_USE_MONOSPACE_FONT
              value: "true"
            - name: PAD_OPTIONS_SHOW_CHAT
              value: "false"
            - name: TRUST_PROXY
              value: "true"
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: etherpad
                  key: ADMIN_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: etherpad
spec:
  type: ClusterIP
  selector:
    app: etherpad
  ports:
  - protocol: TCP
    port: 9001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: etherpad
  annotations:
    kubernetes.io/ingress.class: shared
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: traefik.codemowers.ee
spec:
  rules:
  - host: lauri-etherpad.codemowers.ee
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: etherpad
            port:
              number: 9001
  tls:
  - hosts:
    - "*.codemowers.ee"
